### ISSUE TITLE
Reduce file size of frames

### ISSUE THREAD

**Issue by cedricve** [uug-ai/data-harvesting#12]
Currently we are storing to full frame of the evaluation, which can be of a high resolution, and consumes significant data storage (expensive training). 

<img width="1174" alt="Screenshot 2024-09-02 at 20 41 07" src="https://github.com/user-attachments/assets/14284e29-0303-48ff-a2eb-0409f2256e72">

In most situations only a fraction of the scene is required for training. See below image on the right.

![1725302140](https://github.com/user-attachments/assets/cc5b201b-1902-4d7b-8353-1fca20c22121)

It might be beneficial to crop the image in such way that it contains all the detected objects (rectangles), so we can remove 90% of the image.

If we would agree on this we would need to:
1. Calculate the region of interest
2. Recalculate the boundings boxes of the detection (as x, y) coordinates have changed.

**Comment by tannyle289** [comment]
Implemented, now frame is cropped and only frame with ROIs is saved
![image](https://github.com/user-attachments/assets/8fda1a30-10fa-482d-944d-99b7c6c53ebf)
